# Generated by Django 5.2.5 on 2025-08-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BitCoin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "timestamp",
                    models.PositiveBigIntegerField(
                        db_index=True, help_text="Unix epoch (seconds)"
                    ),
                ),
                (
                    "change_24h_high",
                    models.DecimalField(decimal_places=8, max_digits=20),
                ),
                (
                    "change_24h_low",
                    models.DecimalField(decimal_places=8, max_digits=20),
                ),
            ],
        ),
    ]
