default:
  STATIC_URL: "/static/"
  DATABASES:
    default:
      PASSWORD: UOzOyuamgwaLyLZKoUwZlotOGQLjTWXq
  API_URL: "https://api.api-ninjas.com/v1/bitcoin"
  API_KEY: "n3NTHvrvfEIe+CwuwTQpsw==wrjSxRw4y7HBWbTk"
