default:
  DEBUG: true
  ALLOWED_HOSTS:
    - localhost
    - 127.0.0.1
  DATABASES:
    default:
      ENGINE: django.db.backends.postgresql
      NAME: django_tutorial
      USER: postgres
      PASSWORD: <SECRET>
      HOST: localhost
      PORT: 5432
      TIME_ZONE: Asia/Ho_Chi_Minh
  CELERY:
    BROKER_URL: redis://localhost:6379/0
    CELERY_RESULT_BACKEND: redis://localhost:6379/0
    CELERY_ACCEPT_CONTENT: ["json"]
    CELERY_TASK_SERIALIZER: "json"
    CELERY_RESULT_SERIALIZER: "json"
    CELERY_TIMEZONE: "Asia/Ho_Chi_Minh"
    CELERY_ENABLE_UTC: false
    CELERY_TASK_TRACK_STARTED: true
    CELERY_TASK_TIME_LIMIT: 300
