default:
  DEBUG: true
  ALLOWED_HOSTS:
    - 29958dde6601.ngrok-free.app
    - localhost
    - 127.0.0.1
  DATABASES:
    default:
      ENGINE: django.db.backends.postgresql
      NAME: django_tutorial
      USER: postgres
      PASSWORD: <SECRET>
      HOST: localhost
      PORT: 5432
      TIME_ZONE: Asia/Ho_Chi_Minh
  CELERY:
    broker_url: "redis://localhost:6379/0"
    result_backend: "redis://localhost:6379/0"
    timezone: "Asia/Ho_Chi_Minh"
  API_URL: <SECRET>
  API_KEY: <SECRET>
